### ISSUE TITLE
Error "Page demoAdapterPage2 does not exist " in Lightning

### ISSUE THREAD

**Issue by lrockford** [developerforce/open-cti-demo-adapter#17]
When I add the demo adapter to a lightning app utility bar, I am receiving the error "Page demoAdapterPage2 does not exist".

**Comment by lrockford** [comment]
![image](https://user-images.githubusercontent.com/9937258/35060462-5ed84d00-fb73-11e7-9658-d6a6f322f88c.png)

**Comment by Eric15** [comment]
This page (demoAdapterPage2) actually is missing.  It's not included as one of the components in the downloadable package.

That said, the only reason you're seeing this in the first place is because the first URL (pointing to demoAdapterPage, which does exist) failed to load.

I got the first URL to load by going to Setup --> Call Centers --> EDIT Demo Call Center Adapter --> SET field "CTI Adapter URL" to value "/demoAdapterPage".  Remove the quotes, of course.

Apparently the SF file structure has changed since this package/README was last updated, so the original filepath to the CTI Adapter URL was lost in space.

**Comment by dlouvton** [comment]
updated the repo. It should work now. Thanks!

**Comment by manzanofab** [comment]
@dlouvton no, it still have the same message, I uninstall the app and installed via ANT, I have to create a vf page and called it demoAdapterPage2 and I copy and paste the code of demoAdapterPage into it. That seems to work (just adding this in case others find this handy)

**Comment by nanda9510** [comment]
@lrockford In setup, select call center-> demo adapter->edit and just copy the first URL and paste it in the second one. It definitely works. Good luck!

**Comment by mascot4m** [comment]
Issue is still present, the repo should be updated, in OpenCTI.callCenter is still reference to `demoAdapterPage2`
`<customSettings>{&quot;reqTimeout&quot;:&quot;10000&quot;,&quot;reqStandbyUrl&quot;:&quot;/apex/demoAdapterPage2&quot;,&quot;reqSoftphoneHeight&quot;:&quot;550&quot;,&quot;reqSoftphoneWidth&quot;:&quot;400&quot;,&quot;reqUseApi&quot;:&quot;true&quot;,&quot;reqSalesforceCompatibilityMode&quot;:&quot;Classic_and_Lightning&quot;}</customSettings>`
